### ISSUE TITLE
想做一个简化版本，求改造建议

### ISSUE THREAD

**Issue by yaleimeng** [husky-666/Video_Live_Stream#4]
您这个项目牵涉了许多与B站有关的内容，看上去比较复杂。我这边只想在局域网里面推流。
控制方式是需要播放某个视频的时候，局域网另一台主机发过来一个post请求告知视频的文件名，这边就进行推流。当指定的文件播放完毕后，循环播放一个固定的视频。直到接到新的post指令给定一个新的视频文件名。就停下来播放指定的视频文件。如此循环。
不知道怎样修改或者使用什么样的现有方案更好？盼指教。

**Comment by husky-666** [comment]
1、项目与B站相关的其实只有bilibili直播间弹幕模块，忽略这个模块即可；推流局域网的话，你在本地搭建rtmp推流服务后，把rtmp推流地址改为本地地址即可
2、我想到的可行方法：可以在项目里面额外添加POST请求监听模块，根据POST请求里的视频文件名，执行change.py，应该可以达到你要的效果（其实这个和bilibili直播间弹幕模块有点相似；bilibili直播间弹幕模块是监听直播间的弹幕内容，而你想要的是监听POST请求，那你可以参考bilibili直播间弹幕模块的处理逻辑，来实现POST请求监听模块）

**Comment by husky-666** [comment]
3、当指定的文件播放完毕后，循环播放一个固定的视频；change.py里面有切换播放模式的功能，可以实现重复单集播放（输入：@@R 重复单集播放）

**Comment by husky-666** [comment]
3、当指定的文件播放完毕后，循环播放一个固定的视频；change.py里面有切换播放模式的功能，可以实现重复单集播放（参考README.md里的指令说明）

**Comment by yaleimeng** [comment]
好的。感谢指点
